add_newline = false 
command_timeout = 200
format = "$directory$git_branch$git_status$character"

[character]
error_symbol = "[»](bold #eb6f92)"
success_symbol = "[»](bold #4ecdc4)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
style = "bold #9ccfd8"
repo_root_style = "bold #9ccfd8"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic #c4a7e7"

[git_status]
format     = '[$all_status]($style)'
style      = "#56526e"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = ""
up_to_date = ""
untracked  = ""
modified   = ""
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""
