color_theme = "default"
vim_keys = true
update_ms = 200
proc_sorting = "cpu lazy"
proc_reversed = false
proc_tree = false
proc_colors = true
proc_gradient = true
proc_per_core = false
proc_mem_bytes = true
proc_cpu_graphs = true
show_uptime = true
check_temp = true
cpu_sensor = "Auto"
show_coretemp = true
temp_scale = "celsius"
base_10_sizes = false
cpu_single_graph = false
show_detailed = false
selected_battery = "Auto"
show_battery = true
