theme[main_bg]="#161616"
theme[main_fg]="#dce5e5"

theme[title]="#dce5e5"

theme[hi_fg]="#a1deea"

theme[selected_bg]="#303030"
theme[selected_fg]="#dce5e5"

theme[proc_misc]="#e4c56b"

theme[cpu_box]="#2a2a2a"
theme[mem_box]="#2a2a2a"
theme[net_box]="#2a2a2a"
theme[proc_box]="#2a2a2a"

theme[div_line]="#2a2a2a"

theme[temp_start]="#5fc878"
theme[temp_mid]="#e4c56b"
theme[temp_end]="#e66b80"

theme[cpu_start]="#5fc878"
theme[cpu_mid]="#e4c56b"
theme[cpu_end]="#e66b80"

theme[free_start]="#5fc878"
theme[free_mid]="#e4c56b"
theme[free_end]="#e66b80"

theme[cached_start]="#5fc878"
theme[cached_mid]="#e4c56b"
theme[cached_end]="#e66b80"

theme[available_start]="#5fc878"
theme[available_mid]="#e4c56b"
theme[available_end]="#e66b80"

theme[used_start]="#5fc878"
theme[used_mid]="#e4c56b"
theme[used_end]="#e66b80"

theme[download_start]="#5fc878"
theme[download_mid]="#e4c56b"
theme[download_end]="#e66b80"

theme[upload_start]="#5fc878"
theme[upload_mid]="#e4c56b"
theme[upload_end]="#e66b80"
